import { GraphData } from './types';

export const RIJEKA_GRAPH_DATA: GraphData = {
  nodes: [
    { id: 'GV', name: 'GRADSKO VIJEĆE', type: 'Institution', val: 40 },
    
    // Parties
    { id: 'SDP', name: 'SDP', type: 'Party', val: 25 },
    { id: 'HDZ', name: 'HDZ', type: 'Party', val: 20 },
    { id: 'Most', name: 'Most', type: 'Party', val: 12 },
    { id: 'Mozemo', name: 'Možemo!', type: 'Party', val: 15 },
    { id: 'PGS', name: 'PGS', type: 'Party', val: 15 },
    { id: 'AM', name: 'Akcija mladih', type: 'Party', val: 12 },
    { id: 'Centar', name: 'Centar', type: 'Party', val: 10 },
    { id: 'Alternativa', name: 'Alternativa 101', type: 'Party', val: 10 },
    { id: 'UK', name: 'Unija Kvarnera', type: 'Party', val: 10 },
    { id: 'HSU', name: 'HSU', type: 'Party', val: 10 },
    { id: 'Fokus', name: 'Fokus', type: 'Party', val: 8 },
    { id: 'IDS', name: 'IDS', type: 'Party', val: 8 },
    { id: 'RI', name: 'Lista za Rijeku', type: 'Party', val: 8 },
    { id: 'Nezavisni', name: 'Nezavisni / Nestranački', type: 'Party', val: 15 },

    // Councilors
    { id: 'RobertKurelic', name: 'Robert Kurelić', type: 'Person', val: 10 },
    { id: 'AnetTropeCavar', name: 'Anet Trope Ćavar', type: 'Person', val: 8 },
    { id: 'TanjaSavic', name: 'Tanja Savić', type: 'Person', val: 8 },
    { id: 'JelenaBiondic', name: 'Jelena Biondić', type: 'Person', val: 8 },
    { id: 'JosipOstrogovic', name: 'Josip Ostrogović', type: 'Person', val: 10 },
    { id: 'KatarinaMatakRados', name: 'Katarina Matak Radoš', type: 'Person', val: 8 },
    { id: 'MarkoSmojver', name: 'Marko Smojver', type: 'Person', val: 8 },
    { id: 'MiljenkoKovacevic', name: 'Miljenko Kovačević', type: 'Person', val: 8 },
    { id: 'EneaDessardo', name: 'Enea Dessardo', type: 'Person', val: 8 },
    { id: 'LeonardoMatkovic', name: 'Leonardo Matković', type: 'Person', val: 8 },
    { id: 'StefanMafrici', name: 'Stefan Mataja Mafrici', type: 'Person', val: 8 },
    { id: 'HanaPaleka', name: 'Hana Paleka', type: 'Person', val: 8 },
    { id: 'NebojsaZelic', name: 'Nebojša Zelič', type: 'Person', val: 8 },
    { id: 'RenatoStankovic', name: 'Renato Stanković', type: 'Person', val: 8 },
    { id: 'IrenaBolf', name: 'Irena Bolf', type: 'Person', val: 8 },
    { id: 'IvanaPricaMatijas', name: 'Ivana Prica Matijaš', type: 'Person', val: 8 },
    { id: 'LukaCankovic', name: 'Luka Čanković', type: 'Person', val: 8 },
    { id: 'IgorVlajnic', name: 'Igor Vlajnić', type: 'Person', val: 8 },
    { id: 'MarinRacic', name: 'Marin Račić', type: 'Person', val: 8 },
    { id: 'MasaMagzan', name: 'Maša Magzan', type: 'Person', val: 8 },
    { id: 'SanjinMatijevic', name: 'Sanjin Matijević', type: 'Person', val: 8 },
    { id: 'MarinoMataija', name: 'Marino Mataija', type: 'Person', val: 8 },
    { id: 'RobertSalecic', name: 'Robert Salečić', type: 'Person', val: 8 },
    { id: 'AnaTroselj', name: 'Ana Trošelj', type: 'Person', val: 10 },
    { id: 'TeaBadurina', name: 'Tea Mičić Badurina', type: 'Person', val: 8 },
    { id: 'DamirMikulicic', name: 'Damir Mikuličić', type: 'Person', val: 8 },
    { id: 'VisnjaJelencic', name: 'Višnja Jelenčić', type: 'Person', val: 8 },
    { id: 'AndroAmancic', name: 'Andro Amančić', type: 'Person', val: 8 },
    { id: 'PetraMandic', name: 'Petra Mandić', type: 'Person', val: 10 },
    { id: 'MarinkoKoljanin', name: 'Marinko Koljanin', type: 'Person', val: 8 },
    { id: 'PredragMiletic', name: 'Predrag Miletić', type: 'Person', val: 8 },
    { id: 'SrdanSrdoc', name: 'Srđan Srdoč', type: 'Person', val: 8 },
  ],
  links: [
    // Institutional
    { source: 'SDP', target: 'GV', label: 'sudjeluje', strength: 1 },
    { source: 'HDZ', target: 'GV', label: 'sudjeluje', strength: 1 },
    { source: 'PGS', target: 'GV', label: 'sudjeluje', strength: 1 },

    // Party Memberships
    { source: 'RobertKurelic', target: 'AM', label: 'vijećnik', strength: 2 },
    { source: 'AnetTropeCavar', target: 'AM', label: 'vijećnica', strength: 2 },
    { source: 'TanjaSavic', target: 'Nezavisni', label: 'vijećnica', strength: 2 },
    { source: 'JelenaBiondic', target: 'Nezavisni', label: 'vijećnica', strength: 2 },
    { source: 'JosipOstrogovic', target: 'HDZ', label: 'vijećnik', strength: 2 },
    { source: 'KatarinaMatakRados', target: 'HDZ', label: 'vijećnica', strength: 2 },
    { source: 'MarkoSmojver', target: 'HDZ', label: 'vijećnik', strength: 2 },
    { source: 'MiljenkoKovacevic', target: 'HDZ', label: 'vijećnik', strength: 2 },
    { source: 'EneaDessardo', target: 'Nezavisni', label: 'vijećnik', strength: 2 },
    { source: 'LeonardoMatkovic', target: 'Nezavisni', label: 'vijećnik', strength: 2 },
    { source: 'StefanMafrici', target: 'Nezavisni', label: 'vijećnik', strength: 2 },
    { source: 'HanaPaleka', target: 'Mozemo', label: 'vijećnica', strength: 2 },
    { source: 'NebojsaZelic', target: 'Mozemo', label: 'vijećnica', strength: 2 },
    { source: 'RenatoStankovic', target: 'Mozemo', label: 'vijećnik', strength: 2 },
    { source: 'IrenaBolf', target: 'SDP', label: 'vijećnica', strength: 2 },
    { source: 'IvanaPricaMatijas', target: 'SDP', label: 'vijećnica', strength: 2 },
    { source: 'LukaCankovic', target: 'SDP', label: 'vijećnik', strength: 2 },
    { source: 'IgorVlajnic', target: 'Centar', label: 'vijećnik', strength: 2 },
    { source: 'MarinRacic', target: 'Centar', label: 'vijećnik', strength: 2 },
    { source: 'MasaMagzan', target: 'Alternativa', label: 'vijećnica', strength: 2 },
    { source: 'SanjinMatijevic', target: 'Alternativa', label: 'vijećnik', strength: 2 },
    { source: 'MarinoMataija', target: 'UK', label: 'vijećnik', strength: 2 },
    { source: 'RobertSalecic', target: 'UK', label: 'vijećnik', strength: 2 },
    { source: 'AnaTroselj', target: 'PGS', label: 'vijećnica', strength: 2 },
    { source: 'TeaBadurina', target: 'PGS', label: 'vijećnica', strength: 2 },
    { source: 'DamirMikulicic', target: 'HSU', label: 'vijećnik', strength: 2 },
    { source: 'VisnjaJelencic', target: 'HSU', label: 'vijećnica', strength: 2 },
    { source: 'AndroAmancic', target: 'Fokus', label: 'vijećnik', strength: 2 },
    { source: 'PetraMandic', target: 'Most', label: 'vijećnica', strength: 2 },
    { source: 'MarinkoKoljanin', target: 'Nezavisni', label: 'vijećnik', strength: 2 },
    { source: 'PredragMiletic', target: 'RI', label: 'vijećnik', strength: 2 },
    { source: 'SrdanSrdoc', target: 'IDS', label: 'vijećnik', strength: 2 },

    // Political Alignments (Who sticks together) - Correlates
    { source: 'SDP', target: 'PGS', label: 'koalicija', strength: 4 },
    { source: 'SDP', target: 'HSU', label: 'koalicija', strength: 4 },
    { source: 'SDP', target: 'IDS', label: 'povezani', strength: 3 },
    { source: 'PGS', target: 'HSU', label: 'suradnja', strength: 3 },
    
    { source: 'HDZ', target: 'Most', label: 'oporba - desno', strength: 3 },
    { source: 'AM', target: 'UK', label: 'suradnja', strength: 3 },
    { source: 'AM', target: 'Alternativa', label: 'suradnja', strength: 3 },
    { source: 'Mozemo', target: 'SDP', label: 'suradnja', strength: 3 },
    
    { source: 'Centar', target: 'Alternativa', label: 'često se slažu', strength: 3 },
    { source: 'Nezavisni', target: 'AM', label: 'povezani', strength: 3 },
  ],
};
